design:
    type: ccc
    factors:
        KMER:
            min: 15
            max: 20
            low_init: 16
            high_init: 18
            type: ordinal 
        DVALUE:
            min: 8000
            max: 9000
            low_init: 8300
            high_init: 8800
            type: ordinal
        CLENGTH:
            min: 7000
            max: 8000
            low_init: 7200
            high_init: 7700
            type: ordinal

    responses:
        N50:
            criterion: maximize

working_directory: "/proj/nobackup/b2015353/scaffolding/links_scaffold"

results_file: "N50.txt"

pipeline:
    - LINKSScaffolder
    - CalculateResponse

SLURM:
    account_name: b2015353

LINKSScaffolder:
    script: >
        /usr/bin/perl /proj/nobackup/b2015353/scaffolding/bin/links_v1.8.3/LINKS \
            -f /proj/nobackup/b2015353/scaffolding/genome/FSC771.1.fna \
            -s  /proj/nobackup/b2015353/scaffolding/rawdata/FSC771.fof \
            -b LINKS_output \
            -d  {% DVALUE %}  \
            -k  {% KMER %}   \
            -z  {% CLENGTH %}   


    factors:
        KMER:
            substitute: true
        DVALUE:
            substitute: true
        CLENGTH:
            substitute: true

    SLURM:
        p: core
        n: 4                               #Using >24Gb memory
        t: 00:15:00
        o: slurm.out
        e: slurm.error

CalculateResponse:
    script: >
        python /proj/nobackup/b2015353/scaffolding/bin/response_scoring.py  \
            --fasta  LINKS_output.scaffolds.fa \
            > {% results_file %}
    SLURM:
        p: core
        n: 1
        t: 00:2:00

